NumPyis a Linear Algebra Library for Python. all libraries us numpy as a base for building other libraries.
Numpy is also very fast

## Numpy Tutorial

Import numpy as a library. np is a general convention

In [1]:
import numpy as np

# Numpy
Numpy: Vectors,Arrays,Matrices, and Random Number Generation.


Numpy arrays essentially come in two types: Vectors and Matrices. 
Vectors are strictly 1-d arrays
Matrices are 2-d 
Numpy arrays are a list or list of lists:

In [2]:
list1 = [5,6,7]
list1

[5, 6, 7]

In [3]:
np.array(list1)

array([5, 6, 7])

In [4]:
matrix1 = [[0,1,2],[3,4,5],[6,7,8]]
matrix1

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [5]:
np.array(matrix1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,5)

array([ 0,  5, 10])

Zeros and Ones

Generate arrays of zeros or ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
a = np.zeros((6,6),dtype = int)
a

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [11]:
np.ones((3,3,3),dtype = int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

Return numbers in a range or over a specified interval. default for num is given as 50. Change paramenters to see how it is generated. 

In [ ]:
np.linspace(0,45,15)

## np.linspace(0,10,50).astype(int)


Create an identity matrix or an I matrix

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random numbers

Numpy also has several ways to create random number arrays:


In [ ]:
np.random.rand(20) # generates values between 0 and 1

In [16]:
A = np.random.rand(5,5)
A

array([[0.49077211, 0.98869488, 0.89450469, 0.79303987, 0.99468053],
       [0.81530459, 0.00497266, 0.74872642, 0.83909461, 0.34346221],
       [0.86898491, 0.79519581, 0.10813616, 0.3669288 , 0.76428971],
       [0.92575012, 0.5365439 , 0.42643569, 0.95627838, 0.88631174],
       [0.63409746, 0.6453567 , 0.46924977, 0.87731325, 0.51680889]])

In [17]:
sigma, mean = 3, 15

In [18]:
B = sigma*A + mean

B

array([[16.47231632, 17.96608463, 17.68351406, 17.37911962, 17.9840416 ],
       [17.44591377, 15.01491799, 17.24617925, 17.51728384, 16.03038664],
       [17.60695473, 17.38558744, 15.32440847, 16.1007864 , 17.29286913],
       [17.77725035, 16.6096317 , 16.27930708, 17.86883514, 17.65893523],
       [16.90229237, 16.93607009, 16.40774932, 17.63193974, 16.55042668]])

Return samples from the "standard normal" distribution. Rand function is a uniform distribution. For ex: you will get approximately 20% of the values between 0 and 0.2. 

In [13]:
np.random.randn(25)

array([ 0.91606736, -1.25148185, -1.08700544, -0.80958474, -0.90513413,
       -0.26903863,  1.14451249,  0.93075404,  1.25586271, -0.97601825,
       -0.83114282, -0.80015575, -0.11760685, -0.63759847,  0.04463845,
       -0.93385577, -0.14057952, -0.06314036, -0.59860069,  0.96391503,
        1.45130802, -0.97994861,  1.46860825, -0.59112063,  0.84077713])

In [14]:
np.random.randn(5,5)

array([[ 2.66155695,  0.5056958 , -1.94378968,  0.90993771,  0.75206554],
       [-0.47961846,  0.38297556,  1.79888911,  3.61694627,  0.03455806],
       [ 0.44793383,  1.10067689,  0.48336108, -0.30236705, -0.44284661],
       [-0.5799822 , -0.48178539, -1.52944573, -1.22612222,  0.26490242],
       [-0.42824092, -1.27402601, -0.94000435,  0.34992956, -1.39968111]])

randint
Return random integers from low to high (inclusive).

In [ ]:
np.random.randint(1,100)

In [ ]:
np.random.randint(1,100,10)


Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [20]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr

array([26, 36, 36, 42, 30, 12, 21,  4, 24, 34])

## Reshape
Returns an array containing the same data with a new shape.

In [23]:
arr1 = arr.reshape(5,5)

In [24]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max,min,argmin,argmax

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr[0]=49

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
arr.reshape(25,1).shape
arr

### dtype

You can also grab the data type of the object in the array:

In [ ]:
A

In [ ]:
A.dtype

In [175]:
import numpy as np


In [176]:
n_array = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])


In [180]:
res = np.where(n_array == 0)[0]
print(res)

[ 1  3  5  6 11]


Syntax:

numpy.where(condition[, x, y])

When True, yield x, otherwise yield y

In [181]:
A = np.array([[1,2,3],[2,3,4],[3,4,5]]) # Initialize matrix

In [184]:
A

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [185]:
B = np.array([[2,3,4],[3,4,5],[4,5,6]]) # Initialize another matrix

In [186]:
B

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [187]:
C = A+B # Matrix Addition/Subtraction
C

array([[ 3,  5,  7],
       [ 5,  7,  9],
       [ 7,  9, 11]])

In [188]:
C = A*B #
C 

array([[ 2,  6, 12],
       [ 6, 12, 20],
       [12, 20, 30]])

In [189]:
C = np.dot(A,B)
C

array([[20, 26, 32],
       [29, 38, 47],
       [38, 50, 62]])

In [190]:
A_1 = np.array([[1,2,3],[2,3,4]])
B_1 = np.array([[2,3],[3,4],[4,5]])

In [191]:
C_1 = np.dot(A_1,B_1)
C_1

array([[20, 26],
       [29, 38]])

In [193]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]


In [194]:
result1 = np.cross(p, q)
result2 = np.cross(q, p)
result1

array([ 2, -3])

In [195]:
result2

array([-2,  3])

In [196]:
print(result1==result2)

[False False]


In [197]:
print((result1==result2).shape[0])

2


In [198]:
import numpy as np



In [202]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_id

array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [203]:
i = np.argsort(student_id)
i

array([0, 3, 4, 6, 1, 5, 2], dtype=int64)

In [204]:
print(i[2])

4


### For more on Linear Algebra related functions. visit the following link

https://numpy.org/doc/stable/reference/routines.linalg.html